FROM ubuntu:23.04
COPY ./hermesj/ /app/network/hermesj/
WORKDIR /app
RUN apt-get update && apt-get install -y wget && \
    PLATFORM=`uname -a | awk '{print $(NF-1)}'` && \
    VERSION=v1.6.0 && \
    TARNAME="hermes-${VERSION}-${PLATFORM}-unknown-linux-gnu.tar.gz" && \
    wget "https://github.com/informalsystems/hermes/releases/download/${VERSION}/${TARNAME}" && \
    tar -xf "$TARNAME" && \
    mv ./hermes /usr/local/bin/ && \
    rm -rf "$TARNAME"

CMD /app/network/hermesj/restore-keysj.sh && \
    /app/network/hermesj/create-connj.sh && \
    hermes --config /app/network/hermesj/config.toml create channel --a-chain neutron-test-1 --a-connection connection-0 --a-port transfer --b-port transfer && \
    sleep 20 && \
    /app/network/hermesj/start.sh
