FROM ubuntu:23.04
COPY ./hermes/ /app/network/hermes/
WORKDIR /app
RUN apt-get update && apt-get install -y wget && \
    PLATFORM=`uname -a | awk '{print $(NF-1)}'` && \
    VERSION=v1.6.0 && \
    TARNAME="hermes-${VERSION}-${PLATFORM}-unknown-linux-gnu.tar.gz" && \
    wget "https://github.com/informalsystems/hermes/releases/download/${VERSION}/${TARNAME}" && \
    tar -xf "$TARNAME" && \
    mv ./hermes /usr/local/bin/ && \
    rm -rf "$TARNAME"

RUN chmod +x /app/network/hermes/token-transfer.sh

CMD /app/network/hermes/restore-keys.sh && \
    /app/network/hermes/create-conn.sh && \
    # hermes --config /app/network/hermes/config.toml create channel --a-chain neutron-test-1 --b-chain gaia-test-2 --a-port transfer --b-port transfer --new-client-connection && \
    # sleep 20 && \
    # hermes --config /app/network/hermes/config.toml create channel --a-chain neutron-test-1 --b-chain juno-test-3 --a-port transfer --b-port transfer --new-client-connection && \
    # sleep 20 && \
    # hermes --config /app/network/hermes/config.toml create channel --a-chain neutron-test-1 --b-chain osmosis-test-4 --a-port transfer --b-port transfer --new-client-connection && \
    # sleep 20 && \
    hermes --config /app/network/hermes/config.toml create channel --a-chain neutron-test-1 --a-connection connection-0 --a-port transfer --b-port transfer && \
    sleep 20 && \
    hermes --config /app/network/hermes/config.toml create channel --a-chain neutron-test-1 --a-connection connection-1 --a-port transfer --b-port transfer && \
    sleep 20 && \
    hermes --config /app/network/hermes/config.toml create channel --a-chain neutron-test-1 --a-connection connection-2 --a-port transfer --b-port transfer && \
    sleep 20 && \
    /app/network/hermes/start.sh && \
    sleep 20 && \
    /app/network/hermes/token-transfer.sh
    # hermes tx ft-transfer --denom uatom --config ./network/hermes/config.toml --receiver neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2 --key-name testkey_3 --dst-chain neutron-test-1 --src-chain gaia-test-2 --src-port transfer --src-channel channel-0 --amount 30000000000000 && \
    # sleep 2 && \

    # hermes tx ft-transfer --denom ujuno --config ./network/hermes/config.toml --receiver neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2 --key-name testkey_4 --dst-chain neutron-test-1 --src-chain juno-test-3 --src-port transfer --src-channel channel-0 --amount 40000000000000 && \
    # sleep 2 && \

    # hermes tx ft-transfer --denom uosmo --config ./network/hermes/config.toml --receiver neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2 --key-name testkey_5 --dst-chain neutron-test-1 --src-chain osmosis-test-4 --src-port transfer --src-channel channel-0 --amount 50000000000000 && \
    # sleep 2 && \

