# syntax=docker/dockerfile:1

FROM golang:1.18-alpine AS builderj
RUN apk upgrade -U -a
WORKDIR /src/appj/
COPY --from=appj go.mod go.sum* ./
RUN go mod download
COPY --from=appj . .
ENV PACKAGES curl make git libc-dev bash gcc linux-headers eudev-dev python3
RUN apk add --no-cache $PACKAGES
RUN CGO_ENABLED=0 make install

FROM alpine:latest
WORKDIR /opt/nodej/
COPY --from=setupj . setupj/
ARG BINARY
COPY --from=builderj /go/bin/${BINARY:-gaiad} /usr/local/bin/

EXPOSE 26656 26657 1317 9090
USER 0

CMD sh /opt/nodej/setupj/init.sh && \
  sh /opt/nodej/setupj/init-junod.sh && \
  sh /opt/nodej/setupj/start.sh
